apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "simkes-go"
  # description: Retrieve artist details
spec:
  type: openapi
  lifecycle: experimental
  owner: group:Backend
  consumedBy:
    - component:default/login-page
  definition: |
    openapi: 3.0.0
    info:
      title: Simkes Go API
      version: 1.0.0
    paths: {}