apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "simkes-go"
  links:
    - url: https://dashboard.example.com
      title: My Dashboard
      icon: dashboard
  # description: Retrieve artist details
spec:
  type: openapi
  lifecycle: experimental
  owner: group:Backend
  consumedBy:
    - component:default/login-page
  definition: |
    openapi: 3.0.0
    info:
      license:
        name: SKG
      title: Simkes Go API
      version: 1.0.0
    servers:
      - url: http://simkes.wandek.net/v1
    paths:
      /all:
        get:
          summary: list all Kesiswaan
      /create:
        post:
          summary: create Kesiswaan
