apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: simkes-api
  description: Sistem kesiswaan backend (API Go)
  annotations:
    github.com/project-slug: PT-Ciptadri/simkes-go
spec:
  type: service
  lifecycle: experimental
  owner: user:ZakiAndriansa
