apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "login-page"
  # description: Sistem kesiswaan backend (API Go)
  # annotations:
  #   github.com/project-slug: PT-Ciptadri/simkes-go
spec:
  type: website
  lifecycle: experimental
  owner: group:Backend
  consumesApis:
    - simkes
